apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-thermos
  labels:
    app: thermos
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.thermos.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: thermos
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: thermos
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.thermos.serviceAccountName }}
      serviceAccountName: {{ .Values.thermos.serviceAccountName }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.thermos.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thermos.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thermos.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thermos.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.thermos.additionalInitContainers}}
      initContainers:
        {{- with .Values.thermos.additionalInitContainers }}
          {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}
      containers:
        - name: thermos
          image: "{{ .Values.thermos.image.imageName }}"
          imagePullPolicy: {{ .Values.thermos.image.pullPolicy }}
          command: ["/usr/local/bin/thermos", "--cache-dir", "/tmp/.lookup"]
          workingDir: "/tmp"
          {{- with .Values.thermos.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8180
          livenessProbe:
            httpGet:
              path: /api
              port: 8180
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api
              port: 8180
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-thermos-config
          env:
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-apollo-admin-token
                  key: APOLLO_ADMIN_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-thermos-postgres-secret
                  key: url
            - name: THERMOS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-thermos-postgres-secret
                  key: url
            {{- if .Values.thermos.env }}
            {{- toYaml .Values.thermos.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: cache-volume
              mountPath: /tmp
          resources:
            {{- toYaml .Values.thermos.resources | nindent 12 }}
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-thermos
  labels:
    app: thermos
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.thermos.service.type }}
  ports:
    - port: {{ .Values.thermos.service.port }}
      targetPort: 8180
      protocol: TCP
  selector:
    app: thermos
    release: {{ .Release.Name }}
---
{{- if .Values.thermos.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-thermos
  labels:
    app: thermos
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-thermos
  minReplicas: {{ .Values.thermos.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.thermos.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.thermos.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.thermos.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.thermos.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.thermos.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.thermos.autoscaling.scaleDownStabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.thermos.autoscaling.scaleDownPercent | default 10 }}
        periodSeconds: {{ .Values.thermos.autoscaling.scaleDownPeriodSeconds | default 60 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.thermos.autoscaling.scaleUpStabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.thermos.autoscaling.scaleUpPercent | default 100 }}
        periodSeconds: {{ .Values.thermos.autoscaling.scaleUpPeriodSeconds | default 15 }}
      - type: Pods
        value: {{ .Values.thermos.autoscaling.scaleUpPods | default 4 }}
        periodSeconds: {{ .Values.thermos.autoscaling.scaleUpPeriodSeconds | default 15 }}
      selectPolicy: Max
{{- end }}
