{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "composio.fullname" . }}-frontend
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "composio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "composio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.global.registry.name }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.frontend.service.port | default 3000 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.frontend.service.port | default 3000 }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.frontend.service.port | default 3000 }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-config
          env:
            {{- if .Values.openAI.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openAI.secretRef }}
                  key: {{ .Values.openAI.key }}
            {{- end }}
            {{- if and .Values.frontend.secrets .Values.frontend.secrets.PLAIN_SECRET }}
            - name: PLAIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.frontend.secrets.PLAIN_SECRET.secretName }}
                  key: {{ .Values.frontend.secrets.PLAIN_SECRET.secretKey }}
            {{- else if .Values.frontend.env.PLAIN_SECRET }}
            - name: PLAIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: PLAIN_SECRET
            {{- end }}
            {{- if .Values.frontend.extraEnv }}
            {{- toYaml .Values.frontend.extraEnv | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "composio.fullname" . }}-frontend
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default 3000 }}
      targetPort: {{ .Values.frontend.service.port | default 3000 }}
      protocol: TCP
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "composio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- if and .Values.frontend.autoscaling .Values.frontend.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "composio.fullname" . }}-frontend
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "composio.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.frontend.autoscaling.scaleDownStabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.frontend.autoscaling.scaleDownPercent | default 10 }}
        periodSeconds: {{ .Values.frontend.autoscaling.scaleDownPeriodSeconds | default 60 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.frontend.autoscaling.scaleUpStabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.frontend.autoscaling.scaleUpPercent | default 100 }}
        periodSeconds: {{ .Values.frontend.autoscaling.scaleUpPeriodSeconds | default 15 }}
      - type: Pods
        value: {{ .Values.frontend.autoscaling.scaleUpPods | default 4 }}
        periodSeconds: {{ .Values.frontend.autoscaling.scaleUpPeriodSeconds | default 15 }}
      selectPolicy: Max
{{- end }}
{{- end }}

