apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    app: mcp
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.mcp.replicaCount }}
  selector:
    matchLabels:
      app: mcp
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mcp
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.mcp.serviceAccountName }}
      serviceAccountName: {{ .Values.mcp.serviceAccountName }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.mcp.nodeSelector }}
      nodeSelector:
        {{- with .Values.mcp.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- else }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.mcp.additionalInitContainers}}
      initContainers:
        {{- with .Values.mcp.additionalInitContainers }}
          {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}
      containers:
        - name: mcp
          image: "{{ .Values.mcp.image.imageName }}"
          imagePullPolicy: {{ .Values.mcp.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-mcp-config
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: AUTH_SECRET
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: COMPOSIO_API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-postgres-secret
                  key: url
            {{- if .Values.mcp.env }}
            {{- toYaml .Values.mcp.env | nindent 12 }}
            {{- end }}
          {{- with .Values.mcp.additionalVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mcp.resources | nindent 12 }}
      {{- with .Values.mcp.additionalVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    app: mcp
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.mcp.service.type }}
  ports:
    - port: {{ .Values.mcp.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: mcp
    release: {{ .Release.Name }}
