{{- if and .Values.externalSecrets .Values.externalSecrets.postgres .Values.externalSecrets.postgres.url }}
{{- /* Parse PostgreSQL URL: postgresql://user:password@host:port/database?params */ -}}
{{- $url := .Values.externalSecrets.postgres.url -}}
{{- $withoutProtocol := regexReplaceAll "^[^:]+://" $url "" -}}
{{- $userPassAndRest := regexSplit "@" $withoutProtocol 2 -}}
{{- $userPass := index $userPassAndRest 0 -}}
{{- $hostPortDbParams := index $userPassAndRest 1 -}}
{{- $userPassSplit := regexSplit ":" $userPass 2 -}}
{{- $user := index $userPassSplit 0 -}}
{{- $password := index $userPassSplit 1 -}}
{{- $hostPortAndRest := regexSplit "/" $hostPortDbParams 2 -}}
{{- $hostPort := index $hostPortAndRest 0 -}}
{{- $dbAndParams := index $hostPortAndRest 1 -}}
{{- $hostPortSplit := regexSplit ":" $hostPort 2 -}}
{{- $host := index $hostPortSplit 0 -}}
{{- $port := index $hostPortSplit 1 -}}
{{- $database := regexReplaceAll "\\?.*$" $dbAndParams "" -}}

apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-secret
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  # Original URL for services that need it
  url: {{ .Values.externalSecrets.postgres.url | b64enc }}
  # Individual components for services like Temporal
  host: {{ $host | b64enc }}
  port: {{ $port | b64enc }}
  user: {{ $user | b64enc }}
  password: {{ $password | b64enc }}
  database: {{ $database | b64enc }}
  # Additional Temporal-specific keys
  postgres-password: {{ $password | b64enc }}
{{- end }}