apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-objectstorage-s3"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: "{{ .Release.Name }}-objectstorage-s3-preflight"
    spec:
      {{- if eq .Values.apollo.objectStorage.backend "s3" }}
      collectors:
        # --- Source S3 secrets referenced by your values ---
        - secret:
            name: "{{ .Values.apollo.objectStorage.accessKey.secretName }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.apollo.objectStorage.accessKey.key }}"
            includeValue: false
        - secret:
            name: "{{ .Values.apollo.objectStorage.secretKey.secretName }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.apollo.objectStorage.secretKey.key }}"
            includeValue: false

      analyzers:
        - secret:
            checkName: "S3 access key secret present"
            secretName: "{{ .Values.apollo.objectStorage.accessKey.secretName }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.apollo.objectStorage.accessKey.key }}"
            outcomes:
              - fail:
                  message: "Missing S3 accessKey Secret {{ .Values.apollo.objectStorage.accessKey.secretName }} or key {{ .Values.apollo.objectStorage.accessKey.key }}."
              - pass:
                  message: "Found S3 accessKey Secret."

        - secret:
            checkName: "S3 secret key secret present"
            secretName: "{{ .Values.apollo.objectStorage.secretKey.secretName }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.apollo.objectStorage.secretKey.key }}"
            outcomes:
              - fail:
                  message: "Missing S3 secretKey Secret {{ .Values.apollo.objectStorage.secretKey.secretName }} or key {{ .Values.apollo.objectStorage.secretKey.key }}."
              - pass:
                  message: "Found S3 secretKey Secret."
      {{- else }}
      collectors: []
      analyzers: []
      {{- end }}
