{{- $secretName := include "composio.coreSecretName" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
  name: {{ $secretName }}
type: Opaque
stringData:
  APOLLO_ADMIN_TOKEN: {{ include "apollo-admin-token" . }}
  COMPOSIO_API_KEY: {{ include "composio-api-key" . }}
  ENCRYPTION_KEY: {{ include "encryption-key" . }}
  JWT_SECRET: {{ include "jwt-secret" . }}
  TEMPORAL_TRIGGER_ENCRYPTION_KEY: {{ include "temporal-encryption-key" . }}
{{- end }}
---
