apiVersion: v2
name: composio
description: A Helm chart for Composio
type: application
version: "0.1.39"
appVersion: "0.1.39"
dependencies:
  - name: redis
    version: "17.11.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: temporal
    alias: temporal
    version: "0.68.1"
    repository: "file://./charts/temporal"
    condition: features.temporal
  - name: replicated
    repository: oci://registry.replicated.com/library
    version: 1.12.1
    condition: replicated.enabled 
