{{- if .Values.apollo.dbInit.enabled }}
{{- $randomHash := include "hash" (dict "data" .Values.apollo.image.tag) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-apollo-db-init-{{ $randomHash }}
  labels:
    app: apollo-db-init
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-apollo-db-init-{{ $randomHash }}
      labels:
        app: apollo-db-init
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.apollo.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.apollo.serviceAccount.name  }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.dbInit.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.dbInit.job.restartPolicy | default "OnFailure" }}
      {{- with .Values.apollo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: apollo-db-init
          image: "{{ .Values.global.registry.name }}/{{ .Values.apollo.dbInit.image.repository }}:{{ .Values.apollo.dbInit.image.tag }}"
          imagePullPolicy: {{ .Values.apollo.dbInit.image.pullPolicy }}
          {{- with .Values.apollo.dbInit.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- $coreSecret := include "composio.coreSecretName" . }}
            # Apollo database URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $coreSecret }}
                  key: POSTGRES_URL
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $coreSecret }}
                  key: ENCRYPTION_KEY
            - name: ORG_API_KEY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $coreSecret }}
                  key: ENCRYPTION_KEY
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $coreSecret }}
                  key: COMPOSIO_API_KEY
            - name: ADMIN_EMAIL
              value: {{ .Values.dbInit.adminEmail | default "hello@composio.dev" | quote }}
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  backoffLimit: {{ .Values.dbInit.job.backoffLimit | default 3 }}
  activeDeadlineSeconds: {{ .Values.dbInit.job.activeDeadlineSeconds | default 300 }}
{{- end }}
