apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.apollo.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: apollo
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: apollo
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apollo/apollo-configmap.yaml") . | sha256sum }}
        checksum/env: {{ toYaml .Values.apollo.env | sha256sum }}
    spec:
      {{- if .Values.apollo.serviceAccountName }}
      serviceAccountName: {{ .Values.apollo.serviceAccountName }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apollo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.apollo.nodeSelector }}
      nodeSelector:
        {{- with .Values.apollo.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- else }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.apollo.additionalInitContainers}}
      initContainers:
        {{- with .Values.apollo.additionalInitContainers }}
          {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}
      containers:
        - name: apollo
          image: "{{ .Values.apollo.image.imageName }}"
          imagePullPolicy: {{ .Values.apollo.image.pullPolicy }}
          {{- with .Values.apollo.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9900
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 9900
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 9900
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-apollo-config
          env:
            {{- if eq (default "s3" .Values.apollo.objectStorage.backend) "azure_blob_storage" }}
            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-azure-connection-string
                  key: AZURE_CONNECTION_STRING
            {{- end }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: external-redis-secret
                  key: url
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: COMPOSIO_API_KEY
            {{- if .Values.openAI.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openai-credentials
                  key: OPENAI_API_KEY
            {{- end }}
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-apollo-admin-token
                  key: APOLLO_ADMIN_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: external-postgres-secret
                  key: url
            - name: ORG_API_KEY_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: ENCRYPTION_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-jwt-secret
                  key: JWT_SECRET
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-encryption-key
                  key: ENCRYPTION_KEY
            {{- if .Values.apollo.smtp.enabled }}
            - name: SMTP_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apollo.smtp.credentialsSecret | default (printf "%s-smtp-credentials" .Release.Name) }}
                  key: SMTP_CONNECTION_STRING
            {{- end }}
            {{- if .Values.apollo.env }}
            {{- toYaml .Values.apollo.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.apollo.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.apollo.googleServiceAccount .Values.apollo.googleServiceAccount.enabled }}
            - name: gcp-key
              mountPath: "{{ .Values.apollo.googleServiceAccount.mountPath }}"
              readOnly: true
            {{- end }}
      {{- if and .Values.apollo.googleServiceAccount .Values.apollo.googleServiceAccount.enabled }}
      volumes:
        - name: gcp-key
          secret:
            secretName: {{ .Values.apollo.googleServiceAccount.secretName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.apollo.service.type }}
  ports:
    - port: {{ .Values.apollo.service.port }}
      targetPort: 9900
      protocol: TCP
      {{- if and (eq .Values.apollo.service.type "Port") .Values.apollo.service.Port }}
      Port: {{ .Values.apollo.service.Port }}
      {{- end }}
  selector:
    app: apollo
    release: {{ .Release.Name }}
---
{{- if .Values.apollo.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-apollo
  labels:
    app: apollo
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-apollo
  minReplicas: {{ .Values.apollo.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.apollo.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.apollo.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apollo.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.apollo.autoscaling.scaleDownStabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.apollo.autoscaling.scaleDownPercent | default 10 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleDownPeriodSeconds | default 60 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.apollo.autoscaling.scaleUpStabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.apollo.autoscaling.scaleUpPercent | default 100 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleUpPeriodSeconds | default 15 }}
      - type: Pods
        value: {{ .Values.apollo.autoscaling.scaleUpPods | default 4 }}
        periodSeconds: {{ .Values.apollo.autoscaling.scaleUpPeriodSeconds | default 15 }}
      selectPolicy: Max
{{- end }}
