{{- if and .Values.mercury.enabled .Values.mercury.useKnative }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "composio.fullname" . }}-mercury
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
  annotations:
    # Configure the custom domain for this service
    serving.knative.dev/visibility: cluster-local
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      labels:
        {{- include "composio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mercury
      annotations:
        autoscaling.knative.dev/minScale: "{{ .Values.mercury.autoscaling.minScale | default "1" }}"
        autoscaling.knative.dev/maxScale: "{{ .Values.mercury.autoscaling.maxScale | default "10" }}"
        autoscaling.knative.dev/target: "{{ .Values.mercury.autoscaling.target | default "80" }}"
        # Force new revision only when image changes
        composio.dev/image-tag: "{{ .Values.mercury.image.tag | default .Chart.AppVersion }}"
    spec:
      {{- if .Values.replicated.enabled }}
      {{- include "replicated.imagePullSecrets" . | nindent 6 }}
      {{- end }}
      {{- if not .Values.replicated.enabled }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- end }}
      containerConcurrency: {{ .Values.mercury.containerConcurrency | default 0 }}
      timeoutSeconds: {{ .Values.mercury.timeoutSeconds | default 300 }}
      containers:
        - name: mercury
          image: "{{ include "chart.registry" . }}/{{ .Values.mercury.image.repository }}:{{ .Values.mercury.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mercury.image.pullPolicy }}
          {{- if and .Values.mercury.command (gt (len .Values.mercury.command) 0) }}
          command:
            {{- toYaml .Values.mercury.command | nindent 12 }}
          {{- end }}
          {{- if and .Values.mercury.args (gt (len .Values.mercury.args) 0) }}
          args:
            {{- toYaml .Values.mercury.args | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.mercury.service.port | default 8080 }}
          {{- with .Values.mercury.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- $coreSecret := include "composio.coreSecretName" . }}
            - name: SELF_HOSTED
              value: "true"
            {{- if .Values.openAI.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openAI.secretRef }}
                  key: {{ .Values.openAI.key }}
            {{- end }}
            - name: BACKEND_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: APOLLO_URL
              value: {{ printf "http://%s-apollo:9900" .Release.Name | quote }}
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $coreSecret }}
                  key: COMPOSIO_ADMIN_TOKEN
            - name: USE_APOLLO_GET_DOWNLOAD_URL_API
              value: "true"
          resources:
            {{- toYaml .Values.mercury.resources | nindent 12 }}
          {{- with .Values.mercury.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.mercury.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
 
