{{- if and .Values.mercury.enabled (not .Values.mercury.useKnative) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "composio.fullname" . }}-mercury
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
spec:
  replicas: {{ .Values.mercury.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "composio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mercury
  template:
    metadata:
      labels:
        {{- include "composio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mercury
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.mercury.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mercury.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mercury.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mercury
          image: "{{ .Values.mercury.image.imageName }}"
          imagePullPolicy: {{ .Values.mercury.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mercury.service.port | default 8080 }}
          {{- with .Values.mercury.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.mercury.service.port | default 8080 }}
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.mercury.service.port | default 8080 }}
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-mercury-config
          env:
            {{- if .Values.openAI.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openai-credentials
                  key: OPENAI_API_KEY
            {{- end }}
            - name: APOLLO_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-apollo-admin-token
                  key: APOLLO_ADMIN_TOKEN
            {{- if .Values.otel.enabled }}
            # OTEL Resource attributes
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name={{ .Values.otel.mercury.serviceName | default "mercury-openapi" }},service.version={{ .Values.otel.mercury.serviceVersion | default "1.0.0" }},deployment.environment={{ .Values.otel.environment | default .Values.global.environment | default "development" }}"
            {{- end }}
          resources:
            {{- toYaml .Values.mercury.resources | nindent 12 }}
          {{- with .Values.mercury.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.mercury.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "composio.fullname" . }}-mercury
  namespace: {{ include "composio.namespace" . }}
  labels:
    {{- include "composio.labels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
spec:
  type: {{ .Values.mercury.service.type | default "ClusterIP" }}
  ports:
    - port: 80
      targetPort: {{ .Values.mercury.service.port | default 8080 }}
      protocol: TCP
  selector:
    {{- include "composio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mercury
{{- end }}
