apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-smtp"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: "{{ .Release.Name }}-smtp-preflight"
    spec:
      {{- if .Values.apollo.smtp.enabled }}
      collectors:
        - secret:
            name: "{{ .Values.smtp.password.secretRef }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.smtp.password.key }}"
            includeValue: false

        # Optional: basic TCP connectivity to SMTP host:port (does not validate auth)
        - runPod:
            collectorName: "check-smtp-tcp"
            namespace: "{{ .Release.Namespace }}"
            timeout: 60s
            podSpec:
              restartPolicy: Never
              containers:
                - name: check
                  image: alpine:3.19
                  command: ["/bin/sh", "-c"]
                  args:
                    - |
                      apk add --no-cache busybox-extras >/dev/null 2>&1 || true
                      if nc -vz -w 5 "{{ .Values.smtp.host }}" "{{ .Values.smtp.port }}"; then
                        echo "RESULT=OK"
                      else
                        echo "RESULT=ERROR"
                      fi

      analyzers:
        - secret:
            checkName: "SMTP password source secret present"
            secretName: "{{ .Values.smtp.password.secretRef }}"
            namespace: "{{ .Release.Namespace }}"
            key: "{{ .Values.smtp.password.key }}"
            outcomes:
              - fail:
                  message: "Missing SMTP password Secret {{ .Values.smtp.password.secretRef }} or key {{ .Values.smtp.password.key }}."
              - pass:
                  message: "Found SMTP password Secret."

        - textAnalyze:
            checkName: "SMTP host reachable (TCP)"
            fileName: "/check-smtp-tcp.log"
            regexGroups: 'RESULT=(?P<Result>[A-Z_]+)'
            outcomes:
              - pass:
                  when: 'Result == "OK"'
                  message: "SMTP {{ .Values.smtp.host }}:{{ .Values.smtp.port }} is reachable."
              - fail:
                  message: "Cannot reach SMTP {{ .Values.smtp.host }}:{{ .Values.smtp.port }} from the cluster."
      {{- else }}
      collectors: []
      analyzers: []
      {{- end }}
